- CHANGELOG.md
- lib/Deployer.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/MetadataType.js
- fixes #117 queries not deployable when target is shared DE
- fixes #122 ECONNRESET on caching metadata during deploy
- fixes #127 info: updated automation: undefined
because we are not necessarily caching folders before we cache data extensions when deploying queries - AND we are at the moment removing folders from cache that are not belonging to the current MID, queries that aim to write into shared DEs cant find the target DE's object ID and were blocked from deployment.
I used the already existing cache from parent logic for Dataextensions and added parent cache for folders inside of it.
> Bugfix/ #117 + #122 + #127 query w/ shared DEs, ECONNRESET during caching + bad cli output

- lib/cli.js
- lib/index.js
When createDeltaPkg (index.js) is called from cli.js, 'this' is not an instance of Mcdev hence the error that it can't find _setLoggingLevel.
I've updated the cli.js to call using an arrow function like the other commands. I've also removed the call to _setLoggingLevel from createDeltaPkg, technically this should work now (since the arrow function won't bind this) but I think it makes sense for consistency with the other commands to have the logging level set in the cli configuration.
Please review this change to make sure it makes sense. Whilst I'm confident in the fix, I have only read these two files so have a very limited understanding of the application.
Full error when running 'mcdev createDeltaPkg range Credential/BU' is as follows:
mcdev createDeltaPkg [range] [filter]
Copies …
> #185 - Fix "this._setLoggingLevel is not a function" bug when running mcdev createDeltaPkg

- docs/dist/documentation.md
- lib/metadataTypes/EventDefinition.js
- lib/metadataTypes/FileTransfer.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/MetadataType.js
fix #214 
the total counter for created / updated used to not include records for which errors happened during preDeploySteps but now they do. This required updates to multiple other types than just the initially included fileTransfers
...
- [n/a] README.md updated (if applicable)
- [n/a] CHANGELOG.md updated
> #214 ensure that errors in preDeployTasks are handled gracefully

- README.md
- boilerplate/config.json
- docs/dist/documentation.md
- lib/cli.js
- lib/metadataTypes/Role.js
additional flag for documentation, where one can skip documentation of Standard Roles
anything which is missing from the "base" setup
> Breaking Change: #244 option to document of standard roles (default: off) + `document`  parameters order changed to mirror other commands

- README.md
- docs/dist/documentation.md
- lib/Deployer.js
- lib/index.js
- lib/util/util.js
before we could either go with the config's pre-selection of types for `retrieve` or pass in ONE type.
Now, we can pass in a list of comma-separated types instead.
Same works with `deploy`
...
> Feature/288 allow retrieving+deploying multiple types via cli command

- docs/dist/documentation.md
- lib/Builder.js
- lib/Deployer.js
- lib/cli.js
- lib/index.js
- lib/metadataTypes/AccountUser.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/Email.js
- lib/metadataTypes/EmailSendDefinition.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- lib/metadataTypes/Role.js
- lib/metadataTypes/Script.js
- lib/metadataTypes/TriggeredSendDefinition.js
- lib/util/devops.js
- lib/util/file.js
- lib/util/init.config.js
- lib/util/util.js
- closes #302 
this is helping GUI-based CI/CD to commit the right files by providing a list of extracted code. Specifically, this targets query, script & asset that all store at least 2 files on disk: the metadata.json and the corresponding .sql, .ssjs or .HTML file
this pr aims to provide methods that take BU, type & key and then return a list of paths that identify these non-json code files.
**merge PR #301 first**
> Feature/302 get list of extracted files for given type+key

- lib/util/init.npm.js
- lib/util/util.js
> #441 npm init shows too much output during mcdev init

- boilerplate/files/.vscode/settings.json
- boilerplate/forcedUpdates.json
enhanced IDE experience: markdown files look pretty right away without extra clicks on preview mode button
closes #483
> #483 auto open markdown as preview

- lib/util/util.js
> #539: Util.logger.errorStack no longer always sets exitCode

- lib/metadataTypes/DataExtensionField.js
- test/dataExtension.test.js
- closes #580 
this was reported by a client as a blocker
> #580: Ensure deploy-checks on DE-fields know if DE has data

- package-lock.json
- package.json
Reverts Accenture/sfmc-devtools#588
already fixed on develop branch
> Revert "Bump simple-git from 3.14.1 to 3.15.0"

- boilerplate/config.json
- docs/dist/documentation.md
- lib/util/init.git.js
- lib/util/init.js
- lib/util/util.js
- closes #554 
- fixes #590 
when `mcdev init` is executed it now auto-populates `markets` and `marketList` in the config with actual values based on the retrieved list of BUs. We ask the user which BU is the development BU to properly fill deployment-source vs deployment-target lists. Also, we exclude _ParentBU_ in these market lists.
1. I decided to auto-fill created markets with ONE variable already, `suffix`, and so far, the value we fill is "underscore + buName". That's a placeholder. 
2. Alternatively, we could have no market variables in the markets or an empty suffix parameter, or we could even ask the user for a list of parameters (comma separated) to refill each market with that list of (empty) parameters.
3. In a CI/CD environment with skipInteraction enabled, one can pass in …
> Feature/554 auto generate markets and marketlist upon mcdev init + fixes #590 bug around git user names/emails

- docs/dist/documentation.md
- lib/metadataTypes/List.js
- fixes #566 
I noticed that the previous PR only covered list being a dependency --> when list was cached only. but it didn't cover the retrieve-all-types situation.
> #566: cache all subscriber list from ParentBU even when we retrieving list

- docs/dist/documentation.md
- lib/index.js
- lib/util/config.js
- lib/util/init.js
> #612: fixes mcdev init for joining an existing project

- docs/dist/documentation.md
- lib/MetadataTypeDefinitions.js
- lib/MetadataTypeInfo.js
- lib/metadataTypes/SendClassification.js
- lib/metadataTypes/definitions/SendClassification.definition.js
> #61: add retrieve/cache support for SendClassification

- lib/metadataTypes/Automation.js
- lib/metadataTypes/Query.js
…nd only accessible via SOAP
- fixes #737 
> BUGFIX/737: deleted queries still visible via SOAP api with Status=Inactive

- .fork/.prettierrc
- .fork/custom-commands.json
- .github/ISSUE_TEMPLATE/bug.yml
- boilerplate/files/.vscode/settings.json
- boilerplate/forcedUpdates.json
- docs/dist/documentation.md
- lib/Deployer.js
- lib/Retriever.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/Script.js
- lib/metadataTypes/definitions/Asset.definition.js
- lib/util/devops.js
- lib/util/util.js
- package-lock.json
- package.json
- test/mockRoot/.mcdevrc.json
release
- fixes #761 
- fixes #757
- fixes #753 
- fixes #750 
- fixes #748 
- fixes #747
> Hotfix 4.3.4

- .vscode/extensions.json
- closes #769 
removed:
- todo-tree
- ampscript
- markdown-all-in-one
- vscode-markdownlint
> #769: remove outdated recommendations to increase performance

- lib/metadataTypes/Interaction.js
- fixes #744 
Without the versionNumber parameter specified, the API returns the most recent version of the journey. If that version is in Deleted it cannot be found and hence the error 30003
> bugfix/#744: fix "Interaction matching criteria not found. 30003" during journey retrieve

- docs/dist/documentation.md
- lib/MetadataTypeDefinitions.js
- lib/MetadataTypeInfo.js
- lib/metadataTypes/Event.js
- lib/metadataTypes/Interaction.js
- lib/metadataTypes/definitions/Event.definition.js
- lib/metadataTypes/definitions/Interaction.definition.js
affects: interaction
- closes #777 
...
> #777: rename type eventDefinition to event

- lib/metadataTypes/Event.js
now uses generic method instead of outdated fuelSDK custom logic
- fixes #871 
- [nope] test scripts updated
> #871: fix update for type `event`

- docs/dist/documentation.md
- lib/cli.js
- lib/index.js
- lib/util/cli.js
- test/general.test.js
> #885: make explainTypes work with folder-subtypes & #884 return list of supported metadata types via --json param

- .husky/post-checkout
- closes #914 
also covers main, develop and similar branches. no more hook errors when switching to them
> Task/914 allow standard GitHub branch names to also update gittemplatemessage

- lib/metadataTypes/DataExtensionField.js
- test/type.dataExtension.test.js
> bugfix/#923: corrected dataExtensionField rename log message

- package-lock.json
- package.json
- fixes #893 
confirmed working with live test data when using https://github.com/DougMidgley/SFMC-SDK/issues/229:
> bugfix/#893: retrieving mobileKeyword leads to endlessly requesting next batches / bump sfmc-sdk from 1.0.0 to 1.0.1

- lib/metadataTypes/Automation.js
> #734: run document on postDeploy of automation

- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/Asset.definition.js
- lib/metadataTypes/definitions/Automation.definition.js
- lib/metadataTypes/definitions/DataExtension.definition.js
- lib/metadataTypes/definitions/DataExtract.definition.js
- lib/metadataTypes/definitions/EmailSend.definition.js
- lib/metadataTypes/definitions/Event.definition.js
- lib/metadataTypes/definitions/Filter.definition.js
- lib/metadataTypes/definitions/ImportFile.definition.js
- lib/metadataTypes/definitions/MobileKeyword.definition.js
- lib/metadataTypes/definitions/Query.definition.js
- lib/metadataTypes/definitions/Role.definition.js
- lib/metadataTypes/definitions/TriggeredSend.definition.js
- lib/metadataTypes/definitions/User.definition.js
> bugfix/964: define actual maxKeyLength per type for changeKeyX

- docs/dist/documentation.md
- lib/Deployer.js
- lib/cli.js
- lib/index.js
- lib/util/util.js
- test/utils.js
> bugfix/207: dont create logfile when running helper methods + bugfix/969: log not truncated during test execution

- lib/cli.js
> bugfix/985: ensure trailing commas in key/type lists do not lead to unforeseen executions

- lib/util/cache.js
- test/type.user.test.js
> #1008: ensure deploy returns deployed items, not complete cache

- lib/metadataTypes/User.js
- closes #1012
- closes https://github.com/Accenture/sfmc-devtools/security/code-scanning/15
> #1012: fix potential security issue regarding passwords in log files

- docs/dist/documentation.md
- lib/cli.js
- lib/index.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- lib/util/util.js
- test/resourceFactory.js
- test/resources/9999999/automation/perform-08afb0e2-b00a-4c88-ad2e-1f7f8788c560-response.xml
- test/type.automation.test.js
> Feature/1025 add `schedule` and `deploy --schedule` for automations

- docs/dist/documentation.md
- lib/index.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- test/resources/9999999/automation/perform-08afb0e2-b00a-4c88-ad2e-1f7f8788c560-response.xml
- test/type.automation.test.js
- test/type.query.test.js
> #1034: `pause`, `execute`, `schedule` now return the list of keys that were affected

- test/mockRoot/deploy/testInstance/testBU/fileTransfer/testExisting_fileTransfer.fileTransfer-meta.json
- test/mockRoot/deploy/testInstance/testBU/fileTransfer/testNew_fileTransfer.fileTransfer-meta.json
- test/resources/9999999/automation/v1/filetransfers/72c328ac-f5b0-4e37-91d3-a775666f15a6/patch-response.json
- test/resources/9999999/automation/v1/filetransfers/post-response.json
- test/resources/9999999/automation/v1/ftplocations/get-response.json
- test/resources/9999999/fileTransfer/build-expected.json
- test/resources/9999999/fileTransfer/get-expected.json
- test/resources/9999999/fileTransfer/patch-expected.json
- test/resources/9999999/fileTransfer/post-expected.json
- test/resources/9999999/fileTransfer/template-expected.json
- test/type.fileTransfer.test.js
> task/850: add test class for fileTransfer

- lib/util/util.js
> #1045: remove -error.log file on exit if there was no error

- lib/metadataTypes/Automation.js
- test/resources/9999999/automation/create-testNew_automation-expected.md
- test/resources/9999999/automation/retrieve-testExisting_automation-expected.md
- test/resources/9999999/automation/update-testExisting_automation-expected.md
> Bugfix/1048 rate limit automation retrieval & improve automation schedule documentation

- docs/dist/documentation.md
- lib/index.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/MetadataType.js
- test/type.query.test.js
> Feature/38 add `fixKeys` command - added multi-BU support

- lib/metadataTypes/DataExtension.js
- test/resources/9999999/dataExtension/build-expected.json
- test/resources/9999999/dataExtension/retrieve-expected.json
- test/resources/9999999/dataExtension/retrieve-expected.md
- test/resources/9999999/dataExtension/template-expected.json
- test/resources/9999999/dataExtension/update-expected.json
- test/resources/9999999/dataExtensionField/retrieve-DataExtension.CustomerKey=testExisting_dataExtension-response.xml
- test/resources/9999999/dataExtensionField/retrieve-response.xml
> Bugfix/1097 in the doc md files for `dataExtension`s decimal field type has only precision not scale

- lib/metadataTypes/DataExtension.js
- closes #1133
This fixes the "Some part of your SQL statement is nested too deeply" server error.
I tested by trying to deploy 1000 dataExtensions at once. didn't work with the old approach. did work with the new IN approach
> Bugfix/1133: fix deploying too many dataExtensions blocked by server error

- lib/MetadataTypeDefinitions.js
- lib/MetadataTypeInfo.js
- lib/metadataTypes/DeliveryProfile.js
- lib/metadataTypes/definitions/DeliveryProfile.definition.js
- test/resources/9999999/deliveryProfile/get-expected.json
- test/resources/9999999/legacy/v1/beta/messaging/deliverypolicy/get-response.json
- test/type.deliveryProfile.test.js
> Feature/60: basic retrieve-support for deliveryProfile

- lib/index.js
- closes #1200
messages will only be shown via console.log when methods `deploy` and `retrieve` are executed.
**for Accenture computers:**
**for anyone else:**
> Task/1200 show dedicated messages to accenture and non-accenture users

- lib/Retriever.js
- lib/cli.js
- closes #1272 
find full description in ticket #1273
> Feature/1272 add --metadata option to delete&retrieve

- README.md
> task/1269: mention vscode extension & update copyright year

- lib/cli.js
- lib/index.js
- lib/util/util.js
> task/1281: add new global option --errorLog

- lib/metadataTypes/definitions/DataExtension.definition.js
> TASK/1289: auto-exclude dataExtension _MobileAddressApplication during retrieve

- lib/cli.js
- lib/index.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/DeliveryProfile.definition.js
- lib/metadataTypes/definitions/SendClassification.definition.js
- lib/metadataTypes/definitions/SenderProfile.definition.js
- test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dat_fixKeysSuffix/get-response.json
- test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dat_fixKeysSuffix/patch-response.json
- test/resources/9999999/automation/v1/queries/get-response.json
- test/resources/9999999/query/patch_fixKeysSuffix-expected.json
- test/resources/9999999/query/patch_fixKeysSuffix-expected.sql
- test/resources/9999999/queryDefinition/retrieve-CustomerKey=testExisting_query_fixKeysSuffixANDStatus=Active-response.xml
- test/type.query.test.js
- closes #1302 
- closes #1298 
...
> Feature/1302 + Bugfix/1298 automatically add suffix to key

- lib/util/cli.js
> bugfix/1306: remove empty entry from explainTypes json response

- lib/Builder.js
- lib/cli.js
- lib/index.js
- test/general.test.js
- test/mockRoot/.mcdevrc.json
> Feature/1329 add new method that chains buildtemplate and builddefinition + add --metadata to buildDefinitionBulk

- .beautyamp.json
- .vscode/extensions.json
- .vscode/settings.json
- boilerplate/files/.vscode/settings.json
- boilerplate/forcedUpdates.json
- lib/metadataTypes/Asset.js
- package-lock.json
- package.json
- test/resources/9999999/asset/block-1157-retrieve-expected.html
- test/resources/9999999/asset/v1/content/assets/1295064/get-response.json
- test/resources/9999999/script/get_mixed-expected.html
> Bug/1248 max line width breaks ampscript code in assets + require node >=18.18.2 + bump beauty-amp-core2 to 0.4.9

- lib/cli.js
- closes #1442 
impacts ALL commands that allow using --metadata / -m:
- retrieve
- deploy
- delete
- build
- buildTemplate
- buildDefinition
- buildDefinitionBulk
- execute
- publish
- schedule
- pause
- fixKeys
- replaceContentBlock
> Feature/1442 allow specifying multiple values behind --metadata

- .husky/post-merge
- package-lock.json
- package.json
dependency update that closes a security vulnerability caused by fast-xml-parser 4.4.0
> Bump sfmc-sdk from 2.1.1 to 2.1.2

- lib/metadataTypes/Event.js
- lib/metadataTypes/Journey.js
> bug/1676 fix graceful handling of "key not found" error for journey and event

- boilerplate/files/.vscode/settings.json
- boilerplate/forcedUpdates.json
- closes #1721
the diff view only works on text-only views
> task/1721 disable auto-opening markdown renderer to enable vscode's git diff viewer

- lib/index.js
- lib/util/util.js
- test/resourceFactory.js
> task/2093 no longer auto-recognize vscode extension running mcdev to enable colors in test runs
