- lib/util/init.config.js
- lib/util/util.js
the version check was causing a fatal error when running `mcdev upgrade` 
nope
> CSCLSROZ-623 fix migration from catalyst

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- docs/dist/documentation.md
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/DataExtensionField.definition.js
- lib/metadataTypes/definitions/Folder.definition.js
- lib/util/util.js
- package-lock.json
- package.json
- fixes #100 Handle ECONNRESET errors across various types (incl. Data Extensions)
- fixes #102 block deployment attempt for synchronized Data Extensions with proper error message
- fixes #104 block deployment of shared data extensions on child BUs (existing solution broke somewhere down the line)
- closes #107 rewrite folder to use generic update/create to help with ECONNRESET issue
- closes #108 return full API error messages for create & update via SOAP
- closes #110 improve error message for missing dependencies
The *ECONNRESET* bugs should be gone now for *retrieve* & *deploy* across all types that are enabled by default.
...
> Hotfix/3.0.3 ECONNRESET

- CHANGELOG.md
- lib/metadataTypes/definitions/ImportFile.definition.js
fixes #112
if you have a clue what that weird type id stands for, be my guest :)
> fixes #112 retrieve importFile failing due to missing config

- CHANGELOG.md
- lib/metadataTypes/Automation.js
fixes #118
I merely wrapped the existing code in Util.retryOnError -- that led to a lot of line break changes.
> fixes #118 automation start econnreset not auto-retried

- CHANGELOG.md
- README.md
- docs/dist/documentation.md
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/DataExtensionField.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/Script.definition.js
- lib/util/util.js
- fixed #128 
- fixed #129 
- fixed #132 
- fixed #133 
...
> Bugfix/#128 #129 #132 #133 upsert response not equal to retrieve

- CHANGELOG.md
- README.md
- boilerplate/config.json
- lib/metadataTypes/definitions/AccountUser.definition.js
- package.json
Removes AccountUser as a default retrieve
Closes #146  
That change notes are correct
> #146: Removed AccountUser as default

- CHANGELOG.md
- lib/metadataTypes/DataExtension.js
Added additional filter in processing to remove empty objects
consider if this is the best handling (potentially could rework things to correctly handle errors, rather than returning {}
> #149: filter out empty responses

- .github/dependabot.yml
Changed Dependabot Config to ensure that Target is Develop Branch not Main
Not really
> [TASK] #157 change dependabot target

- docs/dist/documentation.md
- lib/metadataTypes/Automation.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/DataExtract.js
- lib/metadataTypes/EventDefinition.js
- lib/metadataTypes/FileTransfer.js
- lib/metadataTypes/ImportFile.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Script.js
- package-lock.json
- package.json
> Hotfix/i168 bug retrieveAsTemplate bug when using filename prefixes and suffixes

- lib/util/util.js
> #200 fix error on scope tests

- lib/metadataTypes/MetadataType.js
> #202 fix numeric keys not accepted

- lib/index.js
Bugfix to ensure caching for rt
...
> #189 Cache fix for retreive template

- lib/index.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Role.js
Minor fix to ensure ObjectID is retrieved
General apporach
- [NA] CHANGELOG.md updated
- [NA] ran `npm run docs` to update developer docs
> #210: Resolves issues with update of Roles

- lib/metadataTypes/DataExtension.js
fixes #219 
- [n/a] README.md updated (if applicable)
- [n/a] CHANGELOG.md updated
- [n/a] ran `npm run docs` to update developer docs
> #219 inform user about field retrieve after deploy of dataExtension

- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/Role.definition.js
fix #213  
- [-] README.md updated (if applicable)
- [n/a] CHANGELOG.md updated
- [n/a] ran `npm run docs` to update developer docs
> #213 ensure docs/roles file is not overwritten during role deploy

- package-lock.json
- package.json
> Bump fs-extra from 10.0.0 to 10.0.1

- package-lock.json
- package.json
> Bump inquirer from 8.2.0 to 8.2.2

- package-lock.json
- package.json
> Bump lint-staged from 12.3.4 to 12.3.7

- package-lock.json
- package.json
> Bump mocha from 9.2.1 to 9.2.2

- package-lock.json
- package.json
> Bump eslint from 8.9.0 to 8.12.0

- package-lock.json
- package.json
> Bump eslint-config-prettier from 8.4.0 to 8.5.0

- package-lock.json
- package.json
> Bump prettier from 2.5.1 to 2.6.1

- package-lock.json
- package.json
> Bump yargs from 17.3.1 to 17.4.0

- package-lock.json
- package.json
> Bump simple-git from 3.2.6 to 3.5.0

- .github/ISSUE_TEMPLATE/bug.yml
- .github/PULL_REQUEST_TEMPLATE.md
- docs/dist/documentation.md
- lib/cli.js
- lib/index.js
- lib/util/cli.js
- lib/util/util.js
- package.json
- fixes #257 
- fixes #17 
- [n/a] README.md updated (if applicable)
> #257 + #17 skip interaction does not throw error on config issues + correct exit code sent to CI/CD

- lib/index.js
- [] Documentation update
Changed / to path.sep when reading file paths to ensure correct relevance for system (windows vs linux)
simple review
- [N/A] README.md updated (if applicable)
> #260: use path sep to avoid system issues

- lib/metadataTypes/ImportFile.js
- lib/metadataTypes/definitions/ImportFile.definition.js
additional field being added to create payload of importFile
general validate
- [N/A] README.md updated (if applicable)
> #263: Fixes to deploy of Import FIle to all subs

- docs/dist/documentation.md
- lib/util/init.config.js
enhanced upgrade process
- closes #180 
...
- [n/a] README.md updated (if applicable)
> Chore: #180 check blueprint files for changes before trying to override them during upgrade

- LICENSE
- lib/cli.js
- lib/util/init.git.js
- changed 2021 > 2022
- changed ACN internal to external links
> #271: upgrade copyright notice to current year & add support URL

- lib/metadataTypes/DataExtract.js
- lib/metadataTypes/FileTransfer.js
change key from .id to .[idfield in defintion]
tested and good
> #267: retrieveAsTemplate broken for `dataExtract` activity

- lib/util/cache.js
- package.json
closes #279 
should increase performance given that this command is run for each commit and we were essentially running prettier twice so far
...
> Task/279 speed up lint:fix and commit hook

- docs/dist/documentation.md
- lib/util/cli.js
- lib/util/util.js
- fixes #290 
- fixes #291 
...
- [x I have commented my code, particularly in hard-to-understand areas
> Bugfix: #290 mcdev init fails to add 2nd credential + #291mcdev init breaks on updating BUs

- .github/PULL_REQUEST_TEMPLATE.md
- lib/metadataTypes/DataExtension.js
- lib/util/util.js
- test/dataExtension.test.js
- test/resources/9999999/dataExtension/create-expected.json
- test/resources/9999999/dataExtension/update-expected.json
- test/utils.js
> Bugfix/295 dataextension fields not properly formatted in retrieve-folder after de-create

- boilerplate/files/.vscode/settings.json
- docs/dist/documentation.md
- lib/metadataTypes/DataExtension.js
...
- closes #308 
pimps how multi-file metadata is displayed in vscode's latest version. see issue ticket for example
> #308: enhance how multi-file metadata is presented in VSCode

- package-lock.json
- package.json
Bumped to v0.6 of SFMC-SDK to handle errors with more useful messages
Closes #314 
nothing in particular
- [N/A] README.md updated (if applicable)
> #314: SFMC-SDK dep bump

- .github/workflows/code-analysis.yml
Closes #313 - updates codeql to v2
Nothing in particular
> #313: Bump CodeQL version

- boilerplate/config.json
- docs/dist/documentation.md
- lib/Builder.js
- lib/index.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- lib/metadataTypes/Script.js
- lib/util/devops.js
- lib/util/init.config.js
- lib/util/util.js
- types/mcdev.d.js
- closes #300 (breaking change)
- closes #18 
-
**please merge PR #299 first.**
> Feature: #18 include buildtemplate in createdeltapkg + #300 no more key-name swapping in rt

- lib/Builder.js
- lib/Retriever.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/Campaign.js
- lib/metadataTypes/DataExtract.js
- lib/metadataTypes/EventDefinition.js
- lib/metadataTypes/FileTransfer.js
- lib/metadataTypes/ImportFile.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/MobileKeyword.js
- lib/util/auth.js
- lib/util/devops.js
- lib/util/file.js
- test/dataExtension.test.js
- test/query.test.js
- test/resources/9999999/query/build-expected.json
moved all file writing to await because otherwise the order of execution was wrong. This was hidden from tests when tests were expected THEN actual, but it should be actual THEN expected.  - closes #320 
general review
> #320: Test Methods inverted and fixed

- docs/dist/documentation.md
- lib/cli.js
- lib/index.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- lib/metadataTypes/Script.js
- lib/util/file.js
- lib/util/init.config.js
- lib/util/init.git.js
- lib/util/init.js
- lib/util/init.npm.js
- lib/util/util.js
- closes #327 enterprise mismatch errors now include type and value of the found EID to make debugging easy.
- closes #275 
- closes #331 
- closes #332 
...
> #327 enterprise id mismatch, #275 readFile override, #331 `init`/`upgrade` errors, #332 `skipInteraction` always used

- README.md
- lib/index.js
- test/mockRoot/.mcdevrc.json
- closes #338 
- fixes error when trying to update DE without changing fields
**close PR #333 and PR #339 first**
> [Task] #338 disable automatic execution of badkeys upon retrieve

- lib/metadataTypes/MetadataType.js
minor change to handling errors based on default error handling
not in particular
> #367: Fix to use new error handling

- boilerplate/files/.npmrc
- boilerplate/npm-dependencies.json
- lib/util/config.js
- lib/util/init.npm.js
- lib/util/util.js
> Feature/125 ensure eslint + prettier are installed with the same version in the project as in mcdev

- docs/dist/documentation.md
- lib/metadataTypes/Automation.js
> #438: automation docs broken when file trigger is used

- docs/dist/documentation.md
- lib/util/init.js
> #7: fix git commit during mcdev from showing "unsupported type" messages

- README.md
- package.json
- fixes #435 
documentation was updated to explain to contributors that they need to manually run `npx husky install`
> #435 missing husky blocks install via GitHub slows down install when its there

- README.md
- docs/dist/documentation.md
- lib/Deployer.js
- lib/Retriever.js
- lib/index.js
- types/mcdev.d.js
> #443 allow retrieve multiple type key combos at once pkg include

- docs/dist/documentation.md
- lib/metadataTypes/Asset.js
> #449 getfilestocommit fails to return the right value for binary asset types

- lib/metadataTypes/Asset.js
> #452 filepath is not iterable error on getfilestocommit dataextension or asset

- docs/dist/documentation.md
- lib/Deployer.js
> #451 remove deployresult type json files

- lib/metadataTypes/Script.js
> #460 getfilestocommit does not check if script saved html or ssjs file

- lib/metadataTypes/Asset.js
> #463 getfilestocommit broken for asset

- lib/Retriever.js
> #462 retrieve with asset subtype with key not filtering by key

- lib/metadataTypes/Asset.js
> #466 retrievechangelog should return asset subtypes

- .github/workflows/npm-publish.yml
> #469: bump node version in github actions from 14 to 16

- lib/util/devops.js
- lib/util/util.js
> #474 secondary log file just with error messages

- lib/metadataTypes/ImportFile.js
> #479 deploying import file should show better error when destination cannot be resolved

- docs/dist/documentation.md
- lib/Deployer.js
- lib/index.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/MetadataType.js
> #476 deploy should return list of deployed files to deal with automatic key changes

- .vscode/settings.json
- lib/metadataTypes/Query.js
- lib/metadataTypes/Script.js
> #490 builddefinition does not rename extracted sql ssjs files

- lib/metadataTypes/Asset.js
> #494 buildtemplate fails to load binary assets if marketvalues renamed the file

- docs/dist/documentation.md
- lib/Retriever.js
- lib/metadataTypes/Asset.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/ContentArea.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/Email.js
- lib/metadataTypes/EmailSendDefinition.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/Query.js
- lib/metadataTypes/Script.js
- lib/metadataTypes/TriggeredSendDefinition.js
- lib/metadataTypes/definitions/Automation.definition.js
- lib/metadataTypes/definitions/ContentArea.definition.js
- lib/metadataTypes/definitions/DataExtension.definition.js
- lib/metadataTypes/definitions/Email.definition.js
- lib/metadataTypes/definitions/EmailSendDefinition.definition.js
- lib/metadataTypes/definitions/Query.definition.js
- lib/metadataTypes/definitions/Script.definition.js
- lib/metadataTypes/definitions/TriggeredSendDefinition.definition.js
> #498 retrievechangelog does not return folders

- README.md
- docs/dist/documentation.md
- lib/cli.js
- lib/index.js
- lib/util/cli.js
- lib/util/devops.js
- lib/util/init.git.js
- lib/util/init.js
> #501 + #502 bug mcdev init in unattended mode asks if bus should be downloaded

- lib/metadataTypes/DataExtension.js
> #509: folder issue reduced from error to warn

- lib/Deployer.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/Folder.definition.js
> #106 auto create shared de folders

- .github/ISSUE_TEMPLATE/bug.yml
- README.md
- lib/metadataTypes/definitions/Asset.definition.js
- package-lock.json
- package.json
- test/mockRoot/.mcdevrc.json
> 515 bug support asset type template

- boilerplate/gitignore-template
> #525: fixed boilerplate gitignore file to be more specific

- lib/metadataTypes/MetadataType.js
> #522 ensure nothing is returned when the retrieve-keys don't match

- lib/util/init.git.js
- lib/util/init.js
> #543 bug init breaks after asking to download bus

- docs/dist/documentation.md
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/List.js
**tickets**
- closes #565 
- closes #566 
- closes #567 
- closes #579 
**dependencies**
- blocks pr #549
- blocks pr #562
> #565 + #567 improve folder caching & #566 cache global all subs & #579 keep lost lists

- lib/Retriever.js
> #582 error on retrieving one type stops retrieving all following types

- lib/metadataTypes/AccountUser.js
- lib/util/auth.js
> Bugfix/597 some accountUser records broken during retrieve

- docs/dist/documentation.md
- lib/metadataTypes/MetadataType.js
> #594: handle SOAP errors happening during create and retrieve

- .gitignore
- .nycrc.json
- package-lock.json
- package.json
> #550: added Coverage check via NYC

- lib/metadataTypes/definitions/Interaction.definition.js
> #623: enable getting more than first 50 journeys

- lib/util/auth.js
- fixes #621 
awaits update from https://github.com/DougMidgley/SFMC-SDK/pull/153
...
> #621: show batch-msg for REST

- test/dataExtension.test.js
- test/query.test.js
- test/transactionalEmail.test.js
- test/transactionalPush.test.js
- test/transactionalSMS.test.js
- test/utils.js
> #638: ensure token requests are not counted

- docs/dist/documentation.md
- lib/metadataTypes/MetadataType.js
> Bugfix/642 errors during SOAP creates/updates do not lower the number of successful creates/updates

- package.json
> #610: add npm keywords

- lib/Deployer.js
- lib/metadataTypes/DataExtension.js
- closes #641 
- closes #648 
...
-  test scripts updated
-  Wiki updated (if applicable)
> Task/641 cache only relevant fields for deploy dataextension and retrieve by key + #648 show error when nothing to deploy

- lib/metadataTypes/List.js
- test/mockRoot/deploy/testInstance/testBU/transactionalEmail/testExisting_temail.transactionalEmail-meta.json
- test/resources/9999999/messaging/v1/email/definitions/post-response.json
- test/resources/9999999/transactionalEmail/post-expected.json
> #635: fix warnings during test execution

- lib/metadataTypes/EmailSendDefinition.js
- fixes #682 
added checks for surrounding object
> #682: dont fail on ESDs that dont have list or email set

- lib/metadataTypes/definitions/TransactionalEmail.definition.js
- lib/metadataTypes/definitions/TransactionalPush.definition.js
- lib/metadataTypes/definitions/TransactionalSMS.definition.js
- fixes #691 
disabled definitionId for create & update
> #691: fix definitionId error for transactionalSMS / transactionalEmail / transactionalPush update+create

- docs/dist/documentation.md
- lib/Retriever.js
- lib/metadataTypes/Asset.js
- lib/util/util.js
- fixes #693 
- fixes #696 
...
> Bugfix/693 asset sub-subtype template is not parsed + #696 retrieving asset-<subtype> only caches instead

- lib/metadataTypes/Automation.js
- lib/metadataTypes/Interaction.js
- lib/metadataTypes/definitions/Interaction.definition.js
- lib/util/auth.js
- lib/util/util.js
- package.json
- test/interaction.test.js
- test/resourceFactory.js
- test/resources/9999999/interaction/v1/interactions/key_0b76dccf-594c-b6dc-1acf-10c4493dcb84/get-response.json
- test/resources/9999999/interaction/v1/interactions/key_testExisting_interaction/get-response.json
- test/resources/9999999/triggeredSendDefinition/retrieve-response.xml
- fixes #689 
**before:**
**after:**
> Bugfix/689 error during retrieve of interaction fails entire download + remove stats and outcomes from interaction

- .fork/custom-commands.json
- boilerplate/gitignore-template
> Task/702 exclude *.error.log from project repos

- lib/util/auth.js
> #701: reduce severity of connection problem from warn to info

- lib/metadataTypes/TriggeredSendDefinition.js
> #683: find triggeredSends that are used by interaction

- lib/metadataTypes/Asset.js
- lib/metadataTypes/DataExtensionField.js
- lib/metadataTypes/MetadataType.js
> #681: prevent connection problems from failing the entire asset retrieve

- lib/cli.js
> #723: convert deploy param fromRetrieve into option --fromRetrieve

- lib/Deployer.js
> #726: regression fix of folders not getting auto-created during deploy

- .github/ISSUE_TEMPLATE/bug.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/pr-labeler.yml
- .github/workflows/close_issues_on_merge.yml
- .github/workflows/code-analysis.yml
- lib/Deployer.js
- lib/metadataTypes/Automation.js
- package-lock.json
- package.json
- test/mockRoot/.mcdevrc.json
> Hotfix 4.3.3

- .fork/.prettierrc
- .fork/custom-commands.json
- lib/Deployer.js
- fixes #750
example: `mcdev deploy cred/bu asset-template` now works. before, only  `mcdev deploy cred/bu asset` did
> bugfix/750: fix deploying only specified subtype

- lib/util/util.js
> #747: CHORE clean up logs

- docs/dist/documentation.md
- lib/util/devops.js
> Bugfix/757 cdp command does not identify changes in files of a certain type + #761 actually purge deploy folder in cdp 

- lib/Retriever.js
> #753: fix retrieve asset-subtype key

- lib/metadataTypes/Role.js
> task/#768: enhance role documentation readability

- package-lock.json
- package.json
- close #829 
- offers new stuff like the ||= operator
> #829: increase minimum node version to 15.0.0

- .eslintrc.json
- .prettierrc
- boilerplate/files/.prettierrc
- boilerplate/forcedUpdates.json
- lib/metadataTypes/Asset.js
- lib/metadataTypes/Automation.js
- lib/metadataTypes/DataExtension.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/MobileKeyword.js
- lib/metadataTypes/MobileMessage.js
- lib/metadataTypes/Script.js
- lib/metadataTypes/TransactionalEmail.js
- lib/metadataTypes/TransactionalSMS.js
- lib/metadataTypes/User.js
- lib/util/auth.js
- lib/util/businessUnit.js
- lib/util/cli.js
- lib/util/file.js
- lib/util/init.config.js
- lib/util/init.npm.js
- lib/util/util.js
- test/utils.js
> BREAKING CHANGE #829 change minimum node version to 15

- .coverage-comment-template.md
- .coverage-comment-template.svelte
- .github/workflows/coverage-develop-branch.yml
> #861: test

- .github/workflows/coverage-base-update.yml
updates a few more settings for
- #861
> #861: ensure svelte-to-html is installed & steps are properly named

- lib/util/cli.js
> task/906: ensure explainTypes cli output is valid json with double quotes

- .husky/post-checkout
- fixes #914
Any numbers were previously accepted when in fact they should be at the beginning
> #914: ensure numbers are only taken from the start

- lib/index.js
> #892: delete old interaction folder on retrieve of journey

- lib/cli.js
> bugfix/#909: clarify that bd and bdb require the template's file name

- .husky/commit-msg
> bugfix/#936: allow "Revert ..." commit messages

- test/type.user.test.js
> #951: fix test for user-documentation

- .husky/post-checkout
> #959: contributors: ensure commit msg template ends on a space

- .github/dependabot.yml
- closes #975 
copied directly from the docs
> #975: enable dependabot for github-actions

- lib/cli.js
> bugfix/991: group command-options in --help to make it easier to read

- docs/dist/documentation.md
- lib/Deployer.js
- lib/index.js
> #1028: refactoring for fromRetrieve option

- test/mockRoot/deploy/testInstance/testBU/dataExtract/testExisting_dataExtract.dataExtract-meta.json
- test/mockRoot/deploy/testInstance/testBU/dataExtract/testNew_dataExtract.dataExtract-meta.json
- test/resources/9999999/automation/v1/dataextracts/56c5370a-f988-4f36-b0ee-0f876573f6d7/patch-response.json
- test/resources/9999999/automation/v1/dataextracts/post-response.json
- test/resources/9999999/automation/v1/dataextracttypes/get-response.json
- test/resources/9999999/dataExtract/build-expected.json
- test/resources/9999999/dataExtract/get-expected.json
- test/resources/9999999/dataExtract/patch-expected.json
- test/resources/9999999/dataExtract/post-expected.json
- test/resources/9999999/dataExtract/template-expected.json
- test/type.dataExtract.test.js
> Task/846 add test class for `dataExtract`

- lib/util/init.js
> bugfix/934: handle authentication errors during mcdev join gracefully

- lib/metadataTypes/TriggeredSend.js
- lib/metadataTypes/definitions/TriggeredSend.definition.js
- test/mockRoot/deploy/testInstance/testBU/triggeredSend/testExisting_triggeredSend.triggeredSend-meta.json
- test/mockRoot/deploy/testInstance/testBU/triggeredSend/testNew_triggeredSend.triggeredSend-meta.json
- test/resources/9999999/dataFolder/retrieve-ContentType=contextual_suppression_listORContentType=publicationORContentType=suppression_listORContentType=mysubsORContentType=list-response.xml
- test/resources/9999999/dataFolder/retrieve-ContentType=triggered_send_journeybuilderORContentType=triggered_sendORContentType=hidden-response.xml
- test/resources/9999999/email/retrieve-response.xml
- test/resources/9999999/triggeredSend/build-expected.json
- test/resources/9999999/triggeredSend/get-expected.json
- test/resources/9999999/triggeredSend/patch-expected.json
- test/resources/9999999/triggeredSend/post-expected.json
- test/resources/9999999/triggeredSend/template-expected.json
- test/resources/9999999/triggeredSendDefinition/create-response.xml
- test/resources/9999999/triggeredSendDefinition/delete-response.xml
- test/resources/9999999/triggeredSendDefinition/retrieve-TriggeredSendStatusINNew,Active,Inactive,Moved,Canceled-response.xml
- test/resources/9999999/triggeredSendDefinition/update-response.xml
- test/type.automation.test.js
- test/type.triggeredSend.test.js
> task/854: add basic test class for `triggeredSend`

- .github/ISSUE_TEMPLATE/bug.yml
- lib/cli.js
- lib/metadataTypes/Automation.js
- lib/util/init.npm.js
- lib/util/util.js
- package-lock.json
- package.json
- test/mockRoot/.mcdevrc.json
- test/resourceFactory.js
- test/resources/9999999/asset/block-1157-retrieve-expected.html
- test/resources/9999999/asset/block-1157-retrieve-expected.json
- test/resources/9999999/asset/v1/content/assets/1209971/get-response.json
- test/resources/9999999/asset/v1/content/assets/1295064/get-response.json
- test/resources/9999999/asset/v1/content/assets/808714/get-response.json
- test/resources/9999999/asset/v1/content/assets/query/post-response.json
- test/resources/9999999/dataFolder/retrieve-ContentType=asset-sharedORContentType=asset-response.xml
- test/type.asset.test.js
- test/type.automation.test.js
> Release 6.0.1

- docs/dist/documentation.md
- lib/metadataTypes/EmailSend.js
> Bugfix/1139: allow specifying the email ID directly in emailSends

- lib/util/util.js
- closes #1201
...
- [-] test scripts updated
- [-] Wiki updated (if applicable)
> #1201: disable color coding for tests run by GitFork and Sourcetree

- lib/metadataTypes/definitions/SenderProfile.definition.js
forgot retrieve by default in original PR for #54
> #54: activate retrieve-by-default for senderProfile

- lib/Deployer.js
- lib/metadataTypes/Folder.js
- lib/metadataTypes/MetadataType.js
- lib/metadataTypes/definitions/Automation.definition.js
- lib/metadataTypes/definitions/Folder.definition.js
- lib/metadataTypes/definitions/Journey.definition.js
> Feature/1320 support creating journey & automation & triggeredSend-journey folders

- lib/util/cli.js
- lib/util/init.js
> BUG/1332: do not refreshBU on mcdev join

- lib/metadataTypes/Folder.js
> Bug/1410: fix creation of nested journey/automation/journey-triggeredSend folders

- boilerplate/forcedUpdates.json
- boilerplate/gitignore-template
> feature/1463: allow version tracking for /template/ folder

- .fork/custom-commands.json
- .husky/post-checkout
- .husky/post-merge
- closes #1558
newly grouped Create PR commands:
and the completely new commands for Checkout, Merge and Pull
)
> task/1558 add custom git-fork commands pull and switch & pull

- .fork/custom-commands.json
> task/1558: fixes around orgin/branch vs branch

- boilerplate/files/.gitattributes
- boilerplate/forcedUpdates.json
> task/1637 enable syntax highlighting for SSJS files in gitlab

- boilerplate/forcedUpdates.json
- boilerplate/gitignore-template
> task/1679 remove .BAK files that get created by mcdev upgrade from version control

- lib/util/config.js
> Bug/1690 show info how to fix config issues found by VSCE

- boilerplate/files/.prettierrc
- boilerplate/files/eslint.config.js
- boilerplate/forcedUpdates.json
> task/1726 improve linting for .mcdev-validations.js

- lib/metadataTypes/Journey.js
> bug/1738 skip re-retrieve if all publish actions failed

- lib/metadataTypes/Journey.js
> bug/1740 add missing preDeployment handling of journey activities

- lib/Builder.js
- lib/index.js
> task/1805 move purge-deploy-folder logic up to handle multi-type templating

- lib/metadataTypes/DataExtension.js
> bug/1768 fix Fields getting set to empty string after changeKeyField and DE documentation not updated

- .github/ISSUE_TEMPLATE/bug.yml
- package-lock.json
- package.json
- test/mockRoot/.mcdevrc.json
> Update github actions

- lib/util/devops.js
> bug/2030 no longer stop after first no-delta-found source-target map

- lib/metadataTypes/definitions/SendClassification.definition.js
> feature/1989 retrieve sendClassification by default from now on

- lib/metadataTypes/DataExtension.js
> bug/2088: fix javascript error when running deploy

- lib/Builder.js
- lib/Deployer.js
- lib/index.js
- lib/util/config.js
- lib/util/file.js
> task/2096 auto-check config whenever it's loaded

- lib/metadataTypes/Journey.js
> Bug/2100 deleting transactional journeys should also locally delete the associated transactionalEmail

- lib/metadataTypes/MetadataType.js
> bug/2102 add validation rule config setting 'fix'

- lib/cli.js
> feature/2138 add --fix option to retrieve for helping with cleanups of BUs

- lib/metadataTypes/MetadataType.js
> bug/2195 dont fix validation issue if --skipValidation was set

- package-lock.json
- package.json
> task/2209 remove eslint-config-prettier from being a direct dev-dependency

- .github/workflows/code-test.yml
- package.json
> task/2211 drop node 19 support, add test for node 23

- @types/lib/metadataTypes/Journey.d.ts
- @types/lib/metadataTypes/definitions/Journey.definition.d.ts
- lib/metadataTypes/definitions/Journey.definition.js
> task/1707 clearly defined which objectAPIName field is used and how

- lib/metadataTypes/Folder.js
> task/2293 turn "skipping folder" warning into an info message to lower perceived severity
